```{r echo=FALSE}
library(knitr)
opts_chunk$set(message = FALSE,
               warning = FALSE,
               cache = TRUE,
               fig.align = 'center',
               fig.width = 7)
```

# Exploring the data with visualisations {#visualisatingthedata}

## Overview

Before 

## Empirical research into effective data visualisation 

There are no definitive principles for best practices in poster design, but there is a substantial body of literature on data visualisation. This has resulted in some widely repeated basic principles, often motivated by ethical and aesthetic concerns. An example of an ethical concern is the principle that only sequential data can be connected with a line chart, because the line implies a continuous change between the points. Measurement of categories, such as artefact types, locations and methods, should not be linked by lines (for example, there is no continuous sequence between a stone artefact and an animal bone). A related principle is that when absolute magnitudes of the data are important, the vertical axis should begin at zero (Robbins, 2005; Strange, 2007). Displaying data along a vertical axis that does not include zero can misrepresent the data range and exaggerate the relative magnitude between values. ONOe influential set of ideas come from the minimimalist mantras of Tufte. One of his most frequently quoted principles is "maximize the data-ink ratio, within reason". 'Data-ink' refers to the ink used to show data, and so the data-ink ratio is the amount of data-ink relative to the total ink used in a visualisation. These principles ensure that the data are not hidden or distorted by poor choices or irrelevant elements on the visualisation, and that the reader can appreciate the data in the visualisation without distraction and confusion. The practical consequences of this advice include avoiding three-dimensional charts where are two-dimensional chart will suffice (e.g. bar charts and pie charts). Similarly, omitting 'chartjunk' - grids, colours, and artistic elements on the charts - helps to improve the data-ink ratio. 

While these principles have intuitive appeal and are widely repeated, they can lead to highly minimimalist charts that are difficult to interpret [@Tukey1990]. Inbar, Tractinsky and Meyer [-@Inbar2007] and Kulla-Mader [-@kulla2007graphs] found that standard charts where overwhelmingly preferred over Tufte-style minimalist charts.  Kosslyn [-@kosslyn1985graphics] and Carswell [-@carswell1992choosing], have raised the question of how to decide what is data-ink and what is not, concluding that it is frequently highly subjective. Hullman et al., [-@hullman2011benefitting] have suggested that some chartjunk may benefit readers by promoting engagement with the visualisation. For example, Bateman et al. [-@bateman2010useful] and Li and Moacdieh [-@limoacdieh] found that subjects who were shown charts with chartjunk had a significantly higher chance of comprehending the message of the chart as compared to non-embellished charts. Kelly [-@kelly1989data] found no difference in immediate recall of information from high and low data-ink charts in a newspaper format. Similarly, McGurgan [-@mcgurgan2015data] found participants reported similar levels of accuracy and mental effort when answering graph comprehension questions using bar graphs and boxplots with varying data-ink ratios. On the other hand, Gillan and Richman [-@gillan1994minimalism; -@Gillan1992] found empirical support for the principle of data-ink maximization. They found that the percentage of correct interpretations of chart data was significantly lower for the low data-ink charts compared to medium and high data-ink charts. This brief summary of research into the data-ink ratio shows that it is a problematic concept, with only equivocal empirical support. In sum, it seems that principles based on subjective issues of graph aesthetics, often seen Tufte-style graph designs, do not always lead to the most effective visualisations. 

These mixed findings suggest that aesthetic minimalism might not always ensure that our data visualisations are easy to interpret accurately. What, then, are the basic principles for optimising the speed at which a reader can percieve the patterns in the data, and the accuracy of the information that a reader can extract from the visualisation? In the context of a poster presentation these optimisations are highly desirable, as the reader of a poster is typically hoping to get information from a poster much quicker than if they were sitting down reading a scholarly article. 

Cleveland and McGill [-@clevelandmcgill1984] conducted experiments using several common types of data visualisations to test the accuracy with which subjects could read point-values and make comparisons in the data. They found that chart types based on length (such as dot charts and bar charts) were read much more accurately than chart types based on angle, area or volume (such as pie charts and three dimensional charts). Furthermore, they found that people perform substantially worse on stacked bar charts than on aligned bar charts, and that comparisons between adjacent bars are more accurate than between widely separated bars. Numerous subsequent studies have generally supported these findings [@heer2010crowdsourcing; @Kosara2010; @talbot2014four]. Heer and Bostock [-@heer2010crowdsourcing] repicated the core results for comparing sizes across categories, and also found that the addition of gridlines on a plot improved accuracy. Kosara and Ziemkiewicz [-@Kosara2010] tested square pie, or waffle charts (a square divided into 10 x 10 = 100 cells) along with pie, stacked bar and donut charts, and found that respondants were more confident of their reading of square pie charts, and more accurate in reading the chart values, compared to the other types. Zubiaga et al. [-@zubiaga2015knowing] tested respondants with five types of chart (bar charts showing the average value of the distribution, bee swarms, boxplots, stacked bar charts, and histograms) to determine their relative effectiveness in visualising distributions of variables. They find that histograms are the most complete in terms of details given, as well as being the chart type that leads respondants to the most accurate understanding of the underlying data. Rangecroft [-@Rangecroftpie] and Schonlau and Peters [-@schonlau2012comprehension] found that respondants can read 2D pie charts more accurately than 3D pie charts. Zachs et al. [-@zacks1998reading] found a similar result for 2D bar charts over 3D bar charts.

Recent experients have cast some light on the traditional rivalry between pie charts and bar charts [@spence2005no]. For comparison judgements between categories, bars are more accurately judged than pies [@FeldmanStewart2000]. However, for estimates of the proportion of the whole, pie charts were as accurate as bar charts [@simkinhastie; @spence1990visual]. For pair-wise comparisons, pie and bar charts also perform similarly [@spence1991displaying; @meyer1997multiple]. These studies show that under certain conditions, pie charts may be more effective than bar charts. The best choice of chart type depends on the purpose of the chart [@kosslyn1992minding], and the evidence does not support making a universal perscriptions about chart types. 

Although these empirical studies demonstrate a complex relationship between chart type and effectiveness, they can provide a simple, if approximate, rank-order of strategies for visualising data. Dot charts and bar charts are generally at the high-ranking end of the spectrum, along with more exotic styles such as waffle charts and histograms. Lower ranking chart types include stacked bar charts, pie charts. Any kind of 3D chart ranks last. 
